name: Build

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:

      - uses: actions/checkout@v2.3.1

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}      

      - name: install
        run: yarn

      - name: check types
        run: yarn tsc -p . --noEmit

      - name: test
        run: yarn test

      - name: check style
        run: yarn style --check

      - name: build
        run: yarn build
